---
title: "p8105_HW1_jh4054"
author: "Joy Hsu"
date: "9/19/2018"
output: github_document
---

This R markdown document will is for Data Science P8105 - Homework 1
```{r}
#Load tidyverse package
library(tidyverse)
```

#Problem 1

* Create a data frame comprised of 4 variables

```{r}
#set seed for random number generator
set.seed(5)

#create dataframe with tibble package
vector_df = tibble(
  vec_numeric = runif(10,0,5),
  vec_logic = vec_numeric > 2,
  vec_char = c("apples", "banana", "orange", "grapes", "berry", "pear", "grapefruit", "mango", "peach", "durian"),
  vec_factor = factor(c("hairy", "bald", "hairy", "hairy", "bald", "hairy", "hairy", "bald", "hairy", "bald"))
)

vector_df
```
###Explore means
* Mean of numeric vector  
```{r}
mean(vector_df$vec_numeric)
```

* Mean of logic vector
```{r}
mean(vector_df$vec_logic)
```

* Mean of character vector does not work 
```{r}
mean(vector_df$vec_char)
```
    
* Mean of factor vector does not work  
```{r}
mean(vector_df$vec_factor)
```

###Convert variables to numeric values
```{r}
as.numeric(vector_df$vec_char)
as.numeric(vector_df$vec_factor)
```

